##### import numpy package as np

In [2]:
import numpy as np

##### create an empty array of 20 0's and replace the 4rth object with the number 5

In [7]:
a=np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

##### create an array of 20 1's and store it as a variable named array_master. copy the same array into another variable named array_copy

In [10]:
array_master= np.ones(20)
array_copy=array_master.copy()
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

##### create an array containing 30 1's and broadcast all the one's to the value 100

In [13]:
array=np.ones(30)
array[:]=100
array

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

##### create an array of integers starting from 21 until 31 and name it array1
##### create an array of integers starting from 11 until 21 and name it array2
##### calculate the difference between array1 and array2

In [26]:
array1= np.arange(21,31)
array2=np.arange(11,22)[:10]
array1 - array2


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

##### create an array of all even integers from 2 to 10 and name it a1
##### create an array of all even integers from 22 to 30 and name it a2
##### a) use the 2 arrays as rows and create a matrix [hint-usestack function from numpy]

In [29]:
a1=np.arange(2,11,2)
a2=np.arange(22,31,2)
np.stack((a1,a2))


array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

##### b) use the 2 arrays as columns and create a matrix[hint- use column_stack function from numpy]

In [34]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

##### create a 5*6 matrix with values ranging from 0 to 29 and retrieve  the value intersecting at 2 nd row and 3rd column

In [40]:
array_matrix=np.arange(30).reshape(5,6)
array_matrix[1,2]

8

##### create an identity matrix of shape 10*10 and replace the 0's with the value 21

In [43]:
arr=np.eye(10)
arr[arr==0]=21
arr

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

##### use numpy to generate a random set of 10 numbers between 0 and 1
##### display a boolean array output where all values>0.2 are True , rest are marked as False

In [46]:
ar=np.random.rand(10)
ar>0.2

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

##### use numpy to generate an array matrix of 5*2 random numbers sampled from a standard normal distribution 

In [49]:
np.random.randn(5,2)

array([[ 0.01311459, -1.25857659],
       [ 0.79620612,  1.07439517],
       [ 1.29455891,  0.13809063],
       [ 0.22588287, -0.61222366],
       [-0.6799197 , -0.1233215 ]])

##### create an array of 30 linearly spaced points between 0 and 100

In [52]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [54]:



#####numpy indexing and selections

In [71]:
import numpy as np
simple_matrix=np.arange(1,101).reshape(10,10)
print(simple_matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


##### a) retrieve the last 2 rows and first 3 columns values of the above matrix using index and selection technique

In [74]:
simple_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

##### b) retrieve the value 55 from the above matrix using index and selection technique

In [79]:
simple_matrix[5,4]

55

##### c) retrieve the values from the 3rd column in the above matrix 

In [84]:
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

##### d) retrieve the values from the 4rth row in the above matrix

In [87]:
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

##### e) retrieve values from the 2 nd and 4rth rows in the above matrix


In [92]:
simple_matrix[(2,4),:]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [94]:
simple_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])




##### calculate the following values for the given matrix

##### a) calculate sum of all the values in the matrix

In [100]:
simple_matrix.sum()

5050

##### b) calculate standard  deviation of all the values in the matrix

In [104]:
simple_matrix.std()

28.86607004772212

##### c) calculate the variance of all the values in the matrix

In [109]:
simple_matrix.var()

833.25

##### d) calculate the mean of all the values in the matrix

In [113]:
simple_matrix.mean()

50.5

##### e) retrieve the largest number from the matrix

In [118]:
simple_matrix.max()

100

##### retrieve the smallest number from the matrix


In [123]:
simple_matrix.min()

1